import cv2
import numpy as np
from random import randrange
#generated by:Hasan Saleh
trained_face_data = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
webcam=cv2.VideoCapture(0)
while True:
    successful_frame_read , frame = webcam.read()
    grayscaled_img = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    face_coordinates = trained_face_data.detectMultiScale(grayscaled_img)
    for(x,y,w,h) in face_coordinates:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(randrange(256),randrange(256),randrange(256)),10)
    
    #detect face train
    cv2.imshow('Hasan Saleh Face Detector',frame)
    key=cv2.waitKey(1)
    if key==81 or key==113:
        break
        exit()
